<a href="https://colab.research.google.com/github/sharmagaurav43212-rgb/Panda2/blob/main/Panda2.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
df=pd.read_csv("/Zomato-data-.csv")

In [7]:
# Reloading the DataFrame to ensure all original columns are present
df = pd.read_csv('/Zomato-data-.csv')

# Display the head to confirm all columns are back
print("DataFrame reloaded. Original columns:")
display(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/Zomato-data-.csv'

In [8]:
# Rename the 'name' column to 'Rest_Name' permanently
df.rename(columns={"name": "Rest_Name"}, inplace=True)

# Display the head to confirm the rename
print("Column 'name' renamed to 'Rest_Name':")
display(df.head())

NameError: name 'df' is not defined

In [9]:
# Permanently drop the 'votes' column
df.drop("votes", axis=1, inplace=True)

# Display the head to confirm 'votes' column is removed
print("Column 'votes' dropped:")
display(df.head())

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df.rename(columns={"name":"Rest_Name"})  #rename columns
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df.rename(columns={"name":"Rest_Name"},inplace=True)  #permanent rename columns
df.head()

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet

In [ ]:
df.drop("votes",axis=1) #delete column

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [ ]:
df.head()

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet

In [ ]:
df.drop("votes",axis=1,inplace=True) #permanent delete
#df.head()

KeyError: "['votes'] not found in axis"

### Please upload the Zomato dataset

Run the following cell to upload your `Zomato-data-.csv` file from your local machine. A file selection dialog will appear after you execute the cell.

In [10]:
from google.colab import files
import pandas as pd

# This will open a file picker dialog for you to upload the file
uploaded = files.upload()

# Assuming the user uploads a file, we'll get its name
if uploaded:
    # The uploaded dictionary keys are the filenames
    file_name = list(uploaded.keys())[0]
    print(f"File '{file_name}' uploaded successfully. Loading into DataFrame...")

    # Load the uploaded CSV file into a pandas DataFrame
    # If your file has a different name than expected (e.g., 'zomato.csv' instead of 'Zomato-data-.csv'),
    # you might need to adjust the file_name variable or directly use its name.
    df = pd.read_csv(file_name)
    print("DataFrame loaded. Displaying first 5 rows:")
    display(df.head())
else:
    print("No file was uploaded. Please try again.")

# Now, apply the subsequent operations (renaming and dropping 'votes' column)
# if the DataFrame 'df' was successfully loaded.
if 'df' in locals() and not df.empty:
    # Rename the 'name' column to 'Rest_Name' permanently
    df.rename(columns={"name": "Rest_Name"}, inplace=True)
    print("\nColumn 'name' renamed to 'Rest_Name':")
    display(df.head())

    # Permanently drop the 'votes' column
    if 'votes' in df.columns:
        df.drop("votes", axis=1, inplace=True)
        print("\nColumn 'votes' dropped:")
        display(df.head())
    else:
        print("\n'votes' column not found, perhaps already dropped or not present in the dataset.")
else:
    print("DataFrame 'df' was not loaded, skipping further operations.")

Saving Zomato-data-.csv to Zomato-data-.csv
File 'Zomato-data-.csv' uploaded successfully. Loading into DataFrame...
DataFrame loaded. Displaying first 5 rows:

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

Column 'name' renamed to 'Rest_Name':

,Rest_Name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

Column 'votes' dropped:

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet
4,Grand Village,No,No,3.8/5,600,Buffet

In [11]:
# Permanently drop the 'votes' column
if 'votes' in df.columns:
    df.drop("votes", axis=1, inplace=True)
    print("Column 'votes' dropped successfully:")
    display(df.head())
else:
    print("'votes' column was not found. It might have been dropped already or was not in the original dataset.")

'votes' column was not found. It might have been dropped already or was not in the original dataset.

In [ ]:
df.drop(3) #delete row 3

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
4,Grand Village,No,No,600,Buffet
5,Timepass Dinner,Yes,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [ ]:
df.isnull() #missing values

,Rest_Name,online_order,book_table,votes,approx_cost(for two people),listed_in(type)
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
143,False,False,False,False,False,False
144,False,False,False,False,False,False
145,False,False,False,False,False,False
146,False,False,False,False,False,False
147,False,False,False,False,False,False

In [ ]:
df.isnull().sum() #count of missing values

Rest_Name                      0
online_order                   0
book_table                     0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

In [ ]:
df.dropna() #remove missing values

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [ ]:
df.fillna(0) #fill missing values with 0

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df["votes"].fillna(df["votes"].mean(),inplace=True) #fill missing values with mean

/tmp/ipykernel_556/1266658579.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].mean(),inplace=True) #fill missing values with mean

In [ ]:
df["votes"].fillna(df["votes"].median(),inplace=True)

/tmp/ipykernel_556/3857600729.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].median(),inplace=True)

In [ ]:
df["votes"].fillna(df["votes"].mode(),inplace=True)

/tmp/ipykernel_556/3491424634.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].mode(),inplace=True)

In [ ]:
df.duplicated() #duplicate values

0      False
1      False
2      False
3      False
4      False
       ...
143    False
144    False
145    False
146    False
147    False
Length: 148, dtype: bool

In [ ]:
df.duplicated().sum() # count of dublicated values

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True) # Remove duplicates

In [ ]:
df["name"].unique() #unique

array(['Jalsa', 'Spice Elephant', 'San Churro Cafe',
       'Addhuri Udupi Bhojana', 'Grand Village', 'Timepass Dinner',
       'Rosewood International Hotel - Bar & Restaurant', 'Onesta',
       'Penthouse Cafe', 'Smacznego', 'Village Café', 'Cafe Shuffle',
       'The Coffee Shack', 'Caf-Eleven', 'Cafe Vivacity', 'Catch-up-ino',
       "Kirthi's Biryani", 'T3H Cafe', '360 Atoms Restaurant And Cafe',
       'The Vintage Cafe', 'Woodee Pizza', 'Cafe Coffee Day',
       'My Tea House', 'Hide Out Cafe', 'CAFE NOVA', 'Coffee Tindi',
       'Sea Green Cafe', 'Cuppa', "Srinathji's Cafe", 'Redberrys',
       'Foodiction', 'Sweet Truth', 'Ovenstory Pizza', 'Faasos',
       'Behrouz Biryani', 'Fast And Fresh', 'Szechuan Dragon',
       'Empire Restaurant', 'Maruthi Davangere Benne Dosa', 'Chaatimes',
       'Havyaka Mess', "McDonald's", "Domino's Pizza", 'Hotboxit',
       'Kitchen Garden', 'Recipe', 'Beijing Bites', 'Tasty Bytes',
       'Petoo', 'Shree Cool Point', 'Corner House Ice Cream',
       'Biryanis And More', 'Roving Feast', 'FreshMenu',
       'Banashankari Donne Biriyani', 'Wamama', 'Five Star Chicken',
       'XO Belgian Waffle', 'Peppy Peppers', 'Goa 0 Km',
       'Chinese Kitchen', 'Jeet Restaurant', 'Cake of the Day',
       'Kabab Magic', "Namma Brahmin's Idli", 'Gustoes Beer House',
       'Sugar Rush', 'Burger King', 'The Good Bowl', 'The Biryani Cafe',
       'Spicy Tandoor', 'LSD Cafe', 'Rolls On Wheels',
       'Om Sri Vinayaka Chats',
       'Sri Guru Kottureshwara Davangere Benne Dosa',
       'Devanna Dum Biriyani Centre', 'Kolbeh', 'Upahar Sagar',
       'Kadalu Sea Food Restaurant', 'Frozen Bottle', 'Parimala Sweets',
       'Vaishali Deluxe', 'Chill Out', 'The Big O Bakes', 'Meghana Foods',
       'Krishna Sagar', 'Dessert Rose', 'Chickpet Donne Biryani House',
       'Me And My Cake', 'Sunsadm', 'Annapooraneshwari Mess',
       "Thanco's Natural Ice Creams", 'Nandhini Deluxe',
       "Vi Ra's Bar and Restaurant", 'Kaggis', 'Ayda Persian Kitchen',
       'Chatar Patar', 'Polar Bear', "Kidambi's Kitchen", 'Mane Thindi',
       'Kotian Karavali Restaurant', 'Floured-Baked With Love',
       'Cakes & Slices', 'Spice 9', 'Coffee Shopee',
       'Naveen Kabab & Biriyani Mane', 'Katriguppe Donne Biryani',
       'Hari Super Sandwich', 'Atithi Point Ande Ka Funda', 'Just Bake',
       'Dharwad Line Bazaar Mishra Pedha', 'Cake Bite',
       "Aarush's Food Plaza", 'Wood Stove', 'Kulfi & More',
       'Kannadigas Karavali', 'K27 - The Pub', 'Bengaluru Coffee House',
       'New Mangalore Lunch Home', 'Coffee Bytes', 'Parjanya Chat Zone',
       "Kwality Wall's Swirl's Happiness Station", 'Soms Kitchen & Bakes',
       'Banashankari Nati Style', 'Ruchi Maayaka', 'Mohitesh Hut Roll',
       'Sri Basaveshwar Jolada Rotti Oota', 'Roll Magic Fast Food',
       'Foodlieious Multi Cuisine', 'Thanishka Nati And Karavali Style',
       'Swathi Cool Point', 'Kaumudis Juoice', 'Amma - Manae',
       'Sri Sai Tiffannies', 'Hotel Andhra Speices',
       'Sri Murari Family Restaurant', 'Aramane Donne Biriyani',
       'Darkolates', 'Swaada Healthy Kitchen', 'Gawdaru Mane Beriyani',
       'Melting Melodies', 'New Indraprasta', 'Anna Kuteera', 'Darbar',
       'Vijayalakshmi'], dtype=object)

In [ ]:
df["name"].nunique() #count of unique

145

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('dark_background')

In [12]:
# Set pandas options to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Display the entire DataFrame
display(df)

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet
4,Grand Village,No,No,3.8/5,600,Buffet
5,Timepass Dinner,Yes,No,3.8/5,600,Buffet
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,800,Buffet
7,Onesta,Yes,Yes,4.6/5,600,Cafes
8,Penthouse Cafe,Yes,No,4.0/5,700,other
9,Smacznego,Yes,No,4.2/5,550,Cafes
10,Village Café,Yes,No,4.1/5,500,Cafes
11,Cafe Shuffle,Yes,Yes,4.2/5,600,Cafes
12,The Coffee Shack,Yes,Yes,4.2/5,500,Cafes
13,Caf-Eleven,No,No,4.0/5,450,Cafes
14,San Churro Cafe,Yes,No,3.8/5,800,Cafes
15,Cafe Vivacity,Yes,No,3.8/5,650,Cafes
16,Catch-up-ino,Yes,No,3.9/5,800,Cafes
17,Kirthi's Biryani,Yes,No,3.8/5,700,Cafes
18,T3H Cafe,No,No,3.9/5,300,Cafes
19,360 Atoms Restaurant And Cafe,Yes,No,3.1/5,400,Cafes
20,The Vintage Cafe,Yes,No,3.0/5,400,Cafes
21,Woodee Pizza,Yes,No,3.7/5,500,Cafes
22,Cafe Coffee Day,No,No,3.6/5,900,Cafes
23,My Tea House,Yes,No,3.6/5,600,Cafes
24,Hide Out Cafe,No,No,3.7/5,300,Cafes
25,CAFE NOVA,No,No,3.2/5,600,Cafes
26,Coffee Tindi,Yes,No,3.8/5,200,Cafes
27,Sea Green Cafe,No,No,3.3/5,500,Cafes
28,Cuppa,No,No,3.3/5,550,Cafes
29,Srinathji's Cafe,No,No,3.8/5,550,Cafes
30,Redberrys,Yes,No,4.0/5,600,Cafes
31,Foodiction,Yes,No,2.8/5,500,other
32,Sweet Truth,Yes,No,3.9/5,500,Dining
33,Ovenstory Pizza,Yes,No,3.9/5,750,Dining
34,Faasos,Yes,No,4.2/5,500,other
35,Behrouz Biryani,Yes,No,3.9/5,650,Dining
36,Fast And Fresh,Yes,No,2.8/5,400,Dining
37,Szechuan Dragon,Yes,No,4.2/5,600,Dining
38,Empire Restaurant,Yes,No,4.4/5,750,other
39,Maruthi Davangere Benne Dosa,Yes,No,4.0/5,150,Dining
40,Chaatimes,Yes,No,3.8/5,200,Dining
41,Havyaka Mess,No,No,3.9/5,300,Dining
42,McDonald's,Yes,No,3.9/5,500,Dining
43,Domino's Pizza,Yes,No,3.9/5,800,Dining
44,Onesta,Yes,Yes,4.6/5,600,other
45,Hotboxit,No,No,3.8/5,400,Dining
46,Kitchen Garden,Yes,No,3.6/5,300,Dining
47,Recipe,Yes,No,4.0/5,450,Dining
48,Beijing Bites,Yes,No,3.7/5,850,Dining
49,Tasty Bytes,Yes,No,3.1/5,300,Dining
50,Petoo,No,No,3.7/5,450,Dining
51,Shree Cool Point,Yes,No,4.1/5,150,Dining
52,Corner House Ice Cream,No,No,4.3/5,400,Dining
53,Biryanis And More,Yes,No,4.0/5,750,Dining
54,Roving Feast,No,No,4.0/5,450,Dining
55,FreshMenu,Yes,No,3.9/5,450,Dining
56,Banashankari Donne Biriyani,Yes,No,3.8/5,300,Dining
57,Wamama,Yes,Yes,4.2/5,800,other
58,Five Star Chicken,No,No,3.6/5,200,Dining
59,XO Belgian Waffle,Yes,No,3.7/5,400,Dining
60,Peppy Peppers,No,No,4.2/5,800,other
61,Goa 0 Km,Yes,Yes,3.6/5,800,Dining
62,Chinese Kitchen,Yes,No,3.8/5,150,Dining
63,Jeet Restaurant,No,Yes,4.0/5,850,Dining
64,Cake of the Day,No,No,3.7/5,150,Dining
65,Kabab Magic,Yes,No,4.1/5,400,Dining
66,Namma Brahmin's Idli,Yes,No,3.6/5,100,Dining
67,Gustoes Beer House,No,No,4.1/5,700,Dining
68,Sugar Rush,No,No,3.8/5,300,Dining
69,Burger King,Yes,No,3.2/5,600,Dining
70,The Good Bowl,Yes,No,3.6/5,500,Dining
71,The Biryani Cafe,No,No,4.1/5,300,Dining
72,Spicy Tandoor,No,No,4.1/5,150,Dining
73,LSD Cafe,No,No,2.9/5,700,other
74,Rolls On Wheels,No,No,3.6/5,300,Dining
75,Om Sri Vinayaka Chats,No,No,3.6/5,500,Dining
76,Sri Guru Kottureshwara Davangere Benne Dosa,Yes,No,4.1/5,150,Dining
77,Devanna Dum Biriyani Centre,Yes,No,3.6/5,300,Dining
78,Kolbeh,No,No,3.7/5,500,Dining
79,Upahar Sagar,No,No,3.8/5,350,Dining
80,Kadalu Sea Food Restaurant,Yes,No,3.8/5,500,Dining
81,Frozen Bottle,Yes,No,4.2/5,400,Dining
82,Parimala Sweets,No,No,3.5/5,200,Dining
83,Vaishali Deluxe,No,No,3.8/5,700,Dining
84,Chill Out,No,No,3.8/5,100,Dining
85,The Big O Bakes,No,No,4.0/5,300,Dining
86,Meghana Foods,Yes,No,4.4/5,600,Dining
87,Krishna Sagar,No,No,3.5/5,200,Dining
88,Dessert Rose,No,No,3.5/5,500,Dining
89,Chickpet Donne Biryani House,No,No,3.7/5,250,Dining
90,Me And My Cake,No,No,3.7/5,500,Dining
91,Sunsadm,No,No,3.7/5,400,Dining
92,Annapooraneshwari Mess,No,No,3.7/5,200,Dining
93,Thanco's Natural Ice Creams,No,No,3.2/5,300,Dining
94,Nandhini Deluxe,No,No,2.6/5,600,Dining
95,Vi Ra's Bar and Restaurant,No,No,3.3/5,800,Dining
96,Kaggis,No,No,3.8/5,250,Dining
97,Ayda Persian Kitchen,No,No,3.7/5,950,Dining
98,Chatar Patar,No,No,3.7/5,300,Dining
99,Polar Bear,Yes,No,3.8/5,400,Dining
100,Kidambi's Kitchen,No,No,3.5/5,300,Dining
101,Mane Thindi,No,No,3.7/5,200,Dining
102,Kotian Karavali Restaurant,No,No,3.5/5,300,Dining
103,Floured-Baked With Love,No,No,3.8 /5,400,Dining
104,CAFE NOVA,No,No,3.2/5,600,Dining
105,Cakes & Slices,No,No,3.5/5,300,Dining
106,Spice 9,No,No,3.4/5,300,Dining
107,Coffee Shopee,No,No,3.4/5,250,Dining
108,Naveen Kabab & Biriyani Mane,No,No,3.2/5,300,Dining
109,Katriguppe Donne Biryani,No,No,3.2/5,300,Dining
110,Hari Super Sandwich,No,No,3.2/5,200,Dining
111,Atithi Point Ande Ka Funda,No,No,3.1/5,150,Dining
112,Just Bake,No,No,3.4/5,400,Dining
113,Dharwad Line Bazaar Mishra Pedha,No,No,3.4/5,150,Dining
114,Cake Bite,No,No,3.4/5,300,Dining
115,Aarush's Food Plaza,No,No,3.4/5,200,Dining
116,Wood Stove,No,No,3.4/5,150,Dining
117,Kulfi & More,No,No,3.4/5,150,Dining
118,Kannadigas Karavali,No,No,3.4/5,250,Dining
119,K27 - The Pub,No,No,3.1/5,900,Dining
120,Bengaluru Coffee House,Yes,No,4.1/5,300,Dining
121,New Mangalore Lunch Home,No,No,3.3/5,200,Dining
122,Coffee Bytes,No,No,3.1/5,100,Dining
123,Parjanya Chat Zone,No,No,3.3/5,200,Dining
124,Kwality Wall's Swirl's Happiness Station,No,No,2.9/5,200,Dining
125,Soms Kitchen & Bakes,No,No,2.9/5,400,Dining
126,Banashankari Nati Style,No,No,2.9/5,350,Dining
127,Ruchi Maayaka,No,No,3.3/5,100,Dining
128,Mohitesh Hut Roll,No,No,3.3/5,150,Dining
129,Sri Basaveshwar Jolada Rotti Oota,No,No,3.4/5,150,Dining
130,Roll Magic Fast Food,No,No,3.4/5,200,Dining
131,Foodlieious Multi Cuisine,No,No,3.4/5,100,Dining
132,Thanishka Nati And Karavali Style,No,No,3.1/5,400,Dining
133,Swathi Cool Point,No,No,4.1/5,200,Dining
134,Kaumudis Juoice,No,No,3.3/5,150,Dining
135,Amma - Manae,No,No,3.1/5,400,Dining
136,Sri Sai Tiffannies,No,No,3.3/5,150,Dining
137,Hotel Andhra Speices,No,No,2.9/5,250,Dining
138,Sri Murari Family Restaurant,No,No,2.9/5,250,Dining
139,Aramane Donne Biriyani,No,No,2.9/5,150,Dining
140,Darkolates,No,No,3.3/5,200,Dining
141,Swaada Healthy Kitchen,No,No,3.3/5,350,Dining
142,Gawdaru Mane Beriyani,No,No,3.3/5,300,Dining
143,Melting Melodies,No,No,3.3/5,100,Dining
144,New Indraprasta,No,No,3.3/5,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,450,Dining
146,Darbar,No,No,3.0/5,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,200,Dining

In [17]:
df.drop(columns=['url','address','phone','menu_item','dish_linked','reviews_list'], inplace=True, errors='ignore')
df.head()

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet
4,Grand Village,No,No,3.8/5,600,Buffet

In [18]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rest_Name                    148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   approx_cost(for two people)  148 non-null    int64
 5   listed_in(type)              148 non-null    object
dtypes: int64(1), object(5)
memory usage: 7.1+ KB

,Rest_Name,online_order,book_table,rate,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,300,Buffet
4,Grand Village,No,No,3.8/5,600,Buffet

In [21]:
df.drop_duplicates(inplace=True)
df.shape

(148, 6)

In [23]:
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', '2.9/5', '3.5/5', '2.6/5', '3.8 /5', '3.4/5'],
      dtype=object)

In [25]:
def handlerate(value):
  if(value=='NEW' or value=='-'):
    return np.nan
  else:
    value=str(value).split('/')
    value=value[0]
    return float(value)
df['rate']=df['rate'].apply(handlerate)
df['rate'].head()

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64