<a href="https://colab.research.google.com/github/sharmagaurav43212-rgb/Panda2/blob/main/Panda2.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
df=pd.read_csv("/Zomato-data-.csv")

In [2]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [4]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [5]:
df.rename(columns={"name":"Rest_Name"})  #rename columns
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [28]:
df.rename(columns={"name":"Rest_Name"},inplace=True)  #permanent rename columns
df.head()

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet

In [17]:
df.drop("votes",axis=1) #delete column

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [22]:
df.head()

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet

In [21]:
df.drop("votes",axis=1,inplace=True) #permanent delete
#df.head()

KeyError: "['votes'] not found in axis"

In [24]:
df.drop(3) #delete row 3

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
4,Grand Village,No,No,600,Buffet
5,Timepass Dinner,Yes,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [14]:
df.isnull() #missing values

,Rest_Name,online_order,book_table,votes,approx_cost(for two people),listed_in(type)
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
143,False,False,False,False,False,False
144,False,False,False,False,False,False
145,False,False,False,False,False,False
146,False,False,False,False,False,False
147,False,False,False,False,False,False

In [25]:
df.isnull().sum() #count of missing values

Rest_Name                      0
online_order                   0
book_table                     0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

In [26]:
df.dropna() #remove missing values

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [27]:
df.fillna(0) #fill missing values with 0

,Rest_Name,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,800,Buffet
1,Spice Elephant,Yes,No,800,Buffet
2,San Churro Cafe,Yes,No,800,Buffet
3,Addhuri Udupi Bhojana,No,No,300,Buffet
4,Grand Village,No,No,600,Buffet
...,...,...,...,...,...
143,Melting Melodies,No,No,100,Dining
144,New Indraprasta,No,No,150,Dining
145,Anna Kuteera,Yes,No,450,Dining
146,Darbar,No,No,800,Dining
147,Vijayalakshmi,Yes,No,200,Dining

In [31]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [30]:
df["votes"].fillna(df["votes"].mean(),inplace=True) #fill missing values with mean

/tmp/ipykernel_556/1266658579.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].mean(),inplace=True) #fill missing values with mean

In [32]:
df["votes"].fillna(df["votes"].median(),inplace=True)

/tmp/ipykernel_556/3857600729.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].median(),inplace=True)

In [33]:
df["votes"].fillna(df["votes"].mode(),inplace=True)

/tmp/ipykernel_556/3491424634.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["votes"].fillna(df["votes"].mode(),inplace=True)

In [34]:
df.duplicated() #duplicate values

0      False
1      False
2      False
3      False
4      False
       ...
143    False
144    False
145    False
146    False
147    False
Length: 148, dtype: bool

In [35]:
df.duplicated().sum() # count of dublicated values

np.int64(0)

In [39]:
df.drop_duplicates(inplace=True) # Remove duplicates

In [40]:
df["name"].unique() #unique

array(['Jalsa', 'Spice Elephant', 'San Churro Cafe',
       'Addhuri Udupi Bhojana', 'Grand Village', 'Timepass Dinner',
       'Rosewood International Hotel - Bar & Restaurant', 'Onesta',
       'Penthouse Cafe', 'Smacznego', 'Village Café', 'Cafe Shuffle',
       'The Coffee Shack', 'Caf-Eleven', 'Cafe Vivacity', 'Catch-up-ino',
       "Kirthi's Biryani", 'T3H Cafe', '360 Atoms Restaurant And Cafe',
       'The Vintage Cafe', 'Woodee Pizza', 'Cafe Coffee Day',
       'My Tea House', 'Hide Out Cafe', 'CAFE NOVA', 'Coffee Tindi',
       'Sea Green Cafe', 'Cuppa', "Srinathji's Cafe", 'Redberrys',
       'Foodiction', 'Sweet Truth', 'Ovenstory Pizza', 'Faasos',
       'Behrouz Biryani', 'Fast And Fresh', 'Szechuan Dragon',
       'Empire Restaurant', 'Maruthi Davangere Benne Dosa', 'Chaatimes',
       'Havyaka Mess', "McDonald's", "Domino's Pizza", 'Hotboxit',
       'Kitchen Garden', 'Recipe', 'Beijing Bites', 'Tasty Bytes',
       'Petoo', 'Shree Cool Point', 'Corner House Ice Cream',
       'Biryanis And More', 'Roving Feast', 'FreshMenu',
       'Banashankari Donne Biriyani', 'Wamama', 'Five Star Chicken',
       'XO Belgian Waffle', 'Peppy Peppers', 'Goa 0 Km',
       'Chinese Kitchen', 'Jeet Restaurant', 'Cake of the Day',
       'Kabab Magic', "Namma Brahmin's Idli", 'Gustoes Beer House',
       'Sugar Rush', 'Burger King', 'The Good Bowl', 'The Biryani Cafe',
       'Spicy Tandoor', 'LSD Cafe', 'Rolls On Wheels',
       'Om Sri Vinayaka Chats',
       'Sri Guru Kottureshwara Davangere Benne Dosa',
       'Devanna Dum Biriyani Centre', 'Kolbeh', 'Upahar Sagar',
       'Kadalu Sea Food Restaurant', 'Frozen Bottle', 'Parimala Sweets',
       'Vaishali Deluxe', 'Chill Out', 'The Big O Bakes', 'Meghana Foods',
       'Krishna Sagar', 'Dessert Rose', 'Chickpet Donne Biryani House',
       'Me And My Cake', 'Sunsadm', 'Annapooraneshwari Mess',
       "Thanco's Natural Ice Creams", 'Nandhini Deluxe',
       "Vi Ra's Bar and Restaurant", 'Kaggis', 'Ayda Persian Kitchen',
       'Chatar Patar', 'Polar Bear', "Kidambi's Kitchen", 'Mane Thindi',
       'Kotian Karavali Restaurant', 'Floured-Baked With Love',
       'Cakes & Slices', 'Spice 9', 'Coffee Shopee',
       'Naveen Kabab & Biriyani Mane', 'Katriguppe Donne Biryani',
       'Hari Super Sandwich', 'Atithi Point Ande Ka Funda', 'Just Bake',
       'Dharwad Line Bazaar Mishra Pedha', 'Cake Bite',
       "Aarush's Food Plaza", 'Wood Stove', 'Kulfi & More',
       'Kannadigas Karavali', 'K27 - The Pub', 'Bengaluru Coffee House',
       'New Mangalore Lunch Home', 'Coffee Bytes', 'Parjanya Chat Zone',
       "Kwality Wall's Swirl's Happiness Station", 'Soms Kitchen & Bakes',
       'Banashankari Nati Style', 'Ruchi Maayaka', 'Mohitesh Hut Roll',
       'Sri Basaveshwar Jolada Rotti Oota', 'Roll Magic Fast Food',
       'Foodlieious Multi Cuisine', 'Thanishka Nati And Karavali Style',
       'Swathi Cool Point', 'Kaumudis Juoice', 'Amma - Manae',
       'Sri Sai Tiffannies', 'Hotel Andhra Speices',
       'Sri Murari Family Restaurant', 'Aramane Donne Biriyani',
       'Darkolates', 'Swaada Healthy Kitchen', 'Gawdaru Mane Beriyani',
       'Melting Melodies', 'New Indraprasta', 'Anna Kuteera', 'Darbar',
       'Vijayalakshmi'], dtype=object)

In [42]:
df["name"].nunique() #count of unique

145